//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter_History
    {
        public int newsletter_history_id { get; set; }
        public Nullable<int> news_history_newsletter_id { get; set; }
    
        public virtual Newsletter Newsletter { get; set; }
    }
}
