//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_History
    {
        public int note_history_id { get; set; }
        public Nullable<int> note_history_note_id { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
