//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_Loan()
        {
            this.Manage_Loan = new HashSet<Manage_Loan>();
        }
    
        public int personal_loan_id { get; set; }
        public string person_name { get; set; }
        public string person_phone { get; set; }
        public string person_email { get; set; }
        public Nullable<int> loan_amount { get; set; }
        public string loan_detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manage_Loan> Manage_Loan { get; set; }
    }
}
