//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Stock
    {
        public int product_stock_id { get; set; }
        public Nullable<int> product_warehouse_id { get; set; }
        public Nullable<int> prod_stock_prod_manage_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product_Management Product_Management { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
