//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Management
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Management()
        {
            this.Product_Stock = new HashSet<Product_Stock>();
            this.Sale_Management = new HashSet<Sale_Management>();
        }
    
        public int product_manage_id { get; set; }
        public Nullable<int> prod_manag_prod_cat_id { get; set; }
        public string product_name { get; set; }
        public string product_unit { get; set; }
        public string buying_price { get; set; }
        public string selling_price { get; set; }
    
        public virtual Product_Category Product_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Stock> Product_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Management> Sale_Management { get; set; }
    }
}
