//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal_History
    {
        public int proposal_history_id { get; set; }
        public Nullable<int> proposal_history_proposal_id { get; set; }
    
        public virtual Proposal Proposal { get; set; }
    }
}
