//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proposal()
        {
            this.Proposal_History = new HashSet<Proposal_History>();
        }
    
        public int proposal_id { get; set; }
        public Nullable<int> proposal_customer_id { get; set; }
        public string attachment_file { get; set; }
        public Nullable<System.DateTime> propposal_date { get; set; }
        public string proposal_detail { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal_History> Proposal_History { get; set; }
    }
}
