//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Report
    {
        public int purchase_report_id { get; set; }
        public Nullable<int> purchase_report_purchase_id { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
