//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public Nullable<int> report_supp_id { get; set; }
        public Nullable<int> report_manage_supp_id { get; set; }
    
        public virtual Manage_Supplier Manage_Supplier { get; set; }
        public virtual Supply_Management Supply_Management { get; set; }
    }
}
