//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Management
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale_Management()
        {
            this.Sold_History = new HashSet<Sold_History>();
        }
    
        public int sale_id { get; set; }
        public Nullable<int> sale_warehouse_id { get; set; }
        public Nullable<int> sale_customer_id { get; set; }
        public int sale_prod_cat_id { get; set; }
        public Nullable<int> sale_prod_manage_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product_Category Product_Category { get; set; }
        public virtual Product_Management Product_Management { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sold_History> Sold_History { get; set; }
    }
}
