//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Management
    {
        public int supply_manage_id { get; set; }
        public Nullable<int> supply_manage_supp_id { get; set; }
        public Nullable<int> subscribe_status_id { get; set; }
        public Nullable<int> rate { get; set; }
        public string item_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> total_amount { get; set; }
    
        public virtual Manage_Supplier Manage_Supplier { get; set; }
        public virtual Subscribe_Status Subscribe_Status { get; set; }
        public virtual Report Report { get; set; }
    }
}
